spring:
  datasource:
    url: jdbc:mysql://192.168.101.17:3306/mali_oms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.101.18:8848
  application:
    name: mall-order

mybatis-plus:
  mapperLocations: classpath:mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 9000